#!/bin/bash -e
ORGANIZATION_PATH="github.com/CotaPreco"
REPOSITORY_PATH="${ORGANIZATION_PATH}/Horus"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPOSITORY_PATH}
mkdir -p $GOPATH/src/${ORGANIZATION_PATH}
ln -s ${PWD} $GOPATH/src/${REPOSITORY_PATH}
eval $(go env)

CGO_ENABLED=0 go build -a -ldflags '-s' -o build/horus .
