#!/bin/bash -e
ORGANIZATION_PATH="github.com/CotaPreco"
REPOSITORY_PATH="${ORGANIZATION_PATH}/Horus"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPOSITORY_PATH}
mkdir -p $GOPATH/src/${ORGANIZATION_PATH}
ln -s ${PWD} $GOPATH/src/${REPOSITORY_PATH}
eval $(go env)

# deps
go get github.com/stretchr/testify
go get github.com/gorilla/websocket

make tests

# client:php
make -C ./clients/php check-cs
make -C ./clients/php tests
